[package]
name = "analogue"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
proptest = "1.0.0"

[features]

[dependencies]
custom_derive = "0.1.7"
nannou = "0.18.1"
nannou_audio = "0.18.0"
newtype_derive = "0.1.6"

